In [1]:
import os
import gzip
import shutil
import pandas as pd
import argparse
import sys
import os
sys.path.append('/home/ubuntu/repos/learning-habits-analysis')
from utils.data import Subject, load_participant_list
from scipy.io import savemat
import numpy as np

In [49]:
base_dir = '/home/ubuntu/data/learning-habits'
bids_dir = '/home/ubuntu/data/learning-habits/bids_dataset/derivatives/fmriprep-24.0.1-noSDC/'

## fmriprep raw confounds

In [50]:
sub_fmriprep_dir = os.path.join(bids_dir, 'sub-01', 'ses-1', 'func')
raw_confouds_file = os.path.join(sub_fmriprep_dir, 'sub-01_ses-1_task-learning_run-1_desc-confounds_timeseries.tsv')
raw_confounds = pd.read_csv(raw_confouds_file, sep='\t')

In [51]:
raw_confounds.head()

,global_signal,global_signal_derivative1,global_signal_derivative1_power2,global_signal_power2,csf,csf_derivative1,csf_power2,csf_derivative1_power2,white_matter,white_matter_derivative1,...,motion_outlier61,motion_outlier62,motion_outlier63,motion_outlier64,motion_outlier65,motion_outlier66,motion_outlier67,motion_outlier68,motion_outlier69,motion_outlier70
0,1013.857568,NaN,NaN,1.027907e+06,1780.108901,NaN,3.168788e+06,NaN,1019.070593,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1014.594692,0.737124,0.543351,1.029402e+06,1745.868795,-34.240106,3.048058e+06,1172.384882,1014.146322,-4.924271,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1018.276971,3.682280,13.559184,1.036888e+06,1766.456616,20.587821,3.120369e+06,423.858360,1015.566706,1.420384,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1016.898190,-1.378781,1.901038,1.034082e+06,1739.214947,-27.241669,3.024869e+06,742.108524,1013.348342,-2.218364,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1012.529106,-4.369084,19.088895,1.025215e+06,1734.927159,-4.287788,3.009972e+06,18.385122,1010.097655,-3.250688,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [75]:
subjects = load_participant_list(base_dir)

subject = Subject(base_dir, subjects[0], include_modeling=False, include_imaging=True, bids_dir=bids_dir)
        
run = 'learning1'
confounds, _ = subject.load_confounds(run, include_cos=False, scrub=0, fd_thresh=0.5, std_dvars_thresh=None)
#physio_regressors = subject.load_physio_regressors(run)
#confounds = confounds.join(physio_regressors)

bold_file = subject.img.get(run)
mask_file = subject.brain_mask.get(run)
events = getattr(subject, run).events

In [76]:
confounds.head()

,csf,rot_x,rot_y,rot_z,trans_x,trans_y,trans_z,white_matter
0,27.030644,-0.006223,-0.001473,-0.001736,0.105252,-0.096591,0.191707,8.112742
1,-7.209463,-0.004733,-0.001131,-0.001806,0.105262,-0.080687,0.228934,3.188471
2,13.378358,-0.004563,-0.000836,-0.001736,0.119877,-0.141317,0.206122,4.608855
3,-13.863311,-0.004748,-0.000793,-0.001736,0.123522,-0.111331,0.202215,2.390492
4,-18.151099,-0.004514,-0.000530,-0.001736,0.112336,-0.096821,0.210163,-0.860196

In [55]:
confounds['white_matter'].mean()

0.10343401968810334